### PR TITLE
[14.0][IMP] hr_attendance_rfid: Change assertNotEquals to assertNotEqual

### PR DESCRIPTION
**Pull request by victoralmau**
Change assertNotEquals to assertNotEqual

Locked by:
- [x] `hr_attendance_sheet`: https://github.com/OCA/hr-attendance/pull/101

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
CI is red

**Comment by victoralmau** [comment]
CI is green now.

**Comment by victoralmau** [comment]
Now, this is ready to merge.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
