### PR TITLE
[15.0][MIG] hr_attendance_autoclose: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 15.0

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT40357

### CODE REVIEW

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Looks good.

**Comment by nimarosa** [comment]
Tested functional working okay. Merging. 

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@nimarosa please wait for a second review according guidelines.

**Comment by nimarosa** [comment]
@pedrobaeza Sorry my mistake. I saw approved in the PR list and thinked it was the approved tag but was my approval. 
Will try to stop bot action.

**Comment by nimarosa** [comment]
Bot aborted. Waiting for second review.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
