### PR TITLE
[14.0][MIG] hr_attendance_rfid

### PR DESCRIPTION
**Pull request by aphon61bank**
Standard migration.

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
LGTM

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Review by etobella — APPROVED** [review]

**Comment by dsolanki-initos** [comment]
Can we merge this?

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it.

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it.

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it.

**Comment by hkapatel-initos** [comment]
Hello, @pedrobaeza it would be great if could you try to merge it.

**Pull request merged**
