### PR TITLE
[13.0][IMP] hr_attendance_rfid: Add record rule

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
FP -> https://github.com/OCA/hr/pull/833

CC @ForgeFlow

### CODE REVIEW

**Comment by Saran440** [comment]
Please, update code. Thank you.

**Comment by HviorForgeFlow** [comment]
Note: Merge with "minor"

**Review by Saran440 — APPROVED** [review]
Code review :+1:

**Review by jarroyomorales — APPROVED** [review]

**Pull request merged**
