### PR TITLE
[14.0][MIG] hr_attendance_modification_tracking

### PR DESCRIPTION
**Pull request by ao-landoo**
Standard migration to 14.0

### CODE REVIEW

**Comment by ao-landoo** [comment]
@pedrobaeza it's asking for approval

**Comment by pedrobaeza** [comment]
Sorry, I don't use this module. Please look for other reviewers.

**Comment by ao-landoo** [comment]
@Saran440 Can you approve it please?

**Comment by Saran440** [comment]
@ao-landoo This module was PR https://github.com/OCA/hr-attendance/pull/22 already.
Could you review this PR?

**Comment by ao-landoo** [comment]
@Saran440 PR #22 author seems to look inactive and I would like to speed up the migration process if possible.

**Comment by Saran440** [comment]
@ao-landoo Okay, this PR will migrate to V14.
Could you check travis red, please?

**Comment by ao-landoo** [comment]
@Saran440 Travis is now green

**Comment by olgamarcocb** [comment]
An error was raised when testing on runbot:

imagen

Happened when changing manually a check in date on an attendance

**Comment by ao-landoo** [comment]
@jarroyomorales @etobella @Saran440 I'm having a problem will the migration of this module. `check_in` and `check_out` fields have tracking enabled, `tracking=True` in Odoo v14.

The module has a function which depends on `message_ids.tracking_value_ids`, which is related to the fields' tracking. The problem is tracking is not working right and I don't know why. I went to the attendance form view and I modified `check_out` field manually, but the modification was not displayed on chatter until I refreshed browser, I think it's related to the problem I'm having (`@api.depends("message_ids.tracking_value_ids")` is not triggered in test case 5 after write statement).

I recorded a video so you can visualize the problem. Do you have any idea what's going on?

https://user-images.githubusercontent.com/74420754/121654627-36533b80-ca9e-11eb-9af0-4357cb69d0a6.mp4

**Comment by ao-landoo** [comment]
> An error was raised when testing on runbot:
> 
> imagen
> 
> Happened when changing manually a check in date on an attendance

Error has been fixed. Could you try again?

Thanks!

**Review by etobella — APPROVED** [review]
Tested on runbot

**Review by rp-landoo — APPROVED** [review]
Functional test

Worked as expected!

**Comment by ao-landoo** [comment]
@Saran440 can you merge this PR?

**Review by manuelcalerosolis — APPROVED** [review]
Functional review

**Comment by ao-landoo** [comment]
@Saran440 everything should be ready for merge

**Comment by ao-landoo** [comment]
@Saran440 can you merge?

**Comment by Saran440** [comment]
@ao-landoo please, fix red travis.

**Comment by ao-landoo** [comment]
@Saran440 It's ready now

**Pull request merged**
