### PR TITLE
[14.0][FIX] hr_attendance_geolocation: inheritance

### PR DESCRIPTION
**Pull request by chienandalu**
FW of #99 

Use session context to inject position avoiding agressive patching

cc @Tecnativa

please review @pedrobaeza @victoralmau

### CODE REVIEW

**Comment by chienandalu** [comment]
Looks like the branch is red :confused:

**Comment by victoralmau** [comment]
Let me have a few minutes, I have the necessary fix, I will create another PR to solve it.

**Comment by chienandalu** [comment]
Thanks :)

**Review by victoralmau — COMMENTED** [review]
Code review OK (CI fix: https://github.com/OCA/hr-attendance/pull/101).

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge major

**Pull request merged**
