### PR TITLE
[16.0][MIG] hr_attendance_geolocation

### PR DESCRIPTION
**Pull request by ofonseca-pyming**
Standard migration

### CODE REVIEW

**Comment by nimarosa** [comment]
@extrememicro please fix checks to move forward with this migration.

**Comment by ofonseca-pyming** [comment]
@nimarosa  done. Thanks

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/hr-attendance/pull/98 to commit history.

**Comment by ofonseca-pyming** [comment]
@victoralmau , commit included. review it please.
@nimarosa

**Review by nimarosa — APPROVED** [review]

**Comment by victoralmau** [comment]
Functional review OK. Ping @chienandalu

**Review by victoralmau — APPROVED** [review]
Functional review OK. Ping @chienandalu

**Pull request merged**
