### PR TITLE
[14.0] [mig] hr_attendance_autoclose

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
supresed by #20

**Review by dsolanki-initos — APPROVED** [review]
Functional and code review. LGTM

**Comment by fshah-initos** [comment]
Hi @etobella 
It would be nice if you could add reviews here.
Thank you in advance!

**Review by etobella — APPROVED** [review]
No major changes

**Comment by fshah-initos** [comment]
It would be great if we could merge this PR.

**Comment by olgamarcocb** [comment]
LTGM :+1:

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Pull request merged**
