### PR TITLE
[17.0][MIG] hr_attendance_calendar_view: Migration to 17.0

### PR DESCRIPTION
**Pull request by lbarry-apsl**
Module migrated to version 17.0

cc https://github.com/APSL 159331

@miquelalzanillas @BernatObrador @mpascuall @peluko00 @javierobcn @ppyczko please review

### CODE REVIEW

**Comment by peluko00** [comment]
The both commit messages needs to be changed

**Comment by miquelpascual** [comment]
You have to add yourself in the contributors file, not in readme

**Comment by lbarry-apsl** [comment]
> The both commit messages needs to be changed

Done

**Review by ppyczko — APPROVED** [review]
Please rename the pull request following this pattern: [17.0][MIG] \<module\>: Migration to 17.0.
Otherwise, tested in runboat and LGTM.

**Comment by lbarry-apsl** [comment]
> You have to add yourself in the contributors file, not in readme



> Please rename the pull request following this pattern: [17.0][MIG] <module>: Migration to 17.0. Otherwise, tested in runboat and LGTM.

Done, thanks

**Comment by mpascuall** [comment]
LGTM tested in runboat

**Review by miquelpascual — APPROVED** [review]
LGTM tested in runboat

**Review by peluko00 — APPROVED** [review]
LGTM, tested in runboat

**Review by BernatObrador — APPROVED** [review]
LGTM

**Pull request merged**
