### PR TITLE
[16.0] Add module hr_attendance_calendar_view

### PR DESCRIPTION
**Pull request by jo-bloiz-ornot**
Previously added in 15.0
https://github.com/OCA/hr-attendance/pull/122

It's the same module, yet in 16 there can be some tricky interaction where new attendance may not be saved automatically.

### CODE REVIEW

**Comment by jo-bloiz-ornot** [comment]
@nimarosa It is a failure on the github side, right ?

**Review by nimarosa — APPROVED** [review]

**Comment by eicher31** [comment]
I approve this change!

**Review by eicher31 — APPROVED** [review]
LG

**Pull request merged**
