### PR TITLE
[14.0][IMP] hr_attendance_reason: Show reasons on attendance screen

### PR DESCRIPTION
**Pull request by victoralmau**
FWP from 13.0: https://github.com/OCA/hr-attendance/pull/96 + https://github.com/OCA/hr-attendance/pull/111

Show reasons on attendance screen.
ejemplo

Changes done:
- [x] Add configuration option to show reasons in attendance screen.
- [x] Add field to show reason in attendance screen.
- [x] Add sequence to reasons to allow sorted (from kiosk mode).

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT40897

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Please check this error in .po files

`./hr_attendance_reason/i18n/es.po:150: duplicate message definition...
./hr_attendance_reason/i18n/es.po:137: ...this is the location of the first definition
msgmerge: found 1 fatal error`

**Comment by victoralmau** [comment]
> Please check this error in .po files
> 
> `./hr_attendance_reason/i18n/es.po:150: duplicate message definition... ./hr_attendance_reason/i18n/es.po:137: ...this is the location of the first definition msgmerge: found 1 fatal error`

Changes done.

**Comment by pedrobaeza** [comment]
Let's wait till the confirmation of the customer if they finally want the reason as required or not.

**Comment by nimarosa** [comment]
@pedrobaeza Hello Pedro, did you finally determined if your client needs the reason required or not? If we can finally merge this will be helpful to me for an implementation that I'm doing.

**Pull request merged**
