### PR TITLE
[14.0][ADD] hr_attendance_sheet

### PR DESCRIPTION
**Pull request by max3903**
Superseeds #41

### CODE REVIEW

**Comment by max3903** [comment]
@Urvisha-OSI Can you fix this PR?

**Comment by nimarosa** [comment]
@max3903 Please check pre-commit and travis errors so we can review.

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Can you fix this PR?

@max3903 this branch is not longer available
Pr functionality already covered in this PR https://github.com/OCA/hr-attendance/pull/41

**Comment by nimarosa** [comment]
Closing

**Comment by max3903** [comment]
@nimarosa #41 is NOT merged so please reopen one of the 2 PR, they are from the same branch.
@Urvisha-OSI The branch is here: https://github.com/ursais/hr-attendance/tree/14.0_MIG_hr_attendance_sheet

**Comment by nimarosa** [comment]
@max3903 just reopened #41 since if this branch no longer exists it can't be edited. #41 is open now.

**Comment by Urvisha-OSI** [comment]
> @nimarosa #41 is NOT merged so please reopen one of the 2 PR, they are from the same branch. @Urvisha-OSI The branch is here: https://github.com/ursais/hr-attendance/tree/14.0_MIG_hr_attendance_sheet

@max3903 the PR https://github.com/OCA/hr-attendance/pull/41 is open you can merge it

**Pull request closed without merging**
