### PR TITLE
[13.0][FIX] *: Correct website in manifest

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Minor fix. Fast-track.

No need to change the number version.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Something is incorrect...

**Comment by MiquelRForgeFlow** [comment]
The error is fixed in https://github.com/OCA/hr-holidays/pull/4. Once is merged, you can resume this merge 😉

**Pull request merged**
