### PR TITLE
[15.0][MIG] hr_attendance_user_list: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 15.0

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT40348

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this module is not needed existing already "My Attendances" entry. Didn't you see it?

**Comment by nimarosa** [comment]
I think the same of @pedrobaeza , why this module is necessary?

**Comment by victoralmau** [comment]
Ok, sorry, you are right, but what about the pivot view that this module adds?

**Comment by pedrobaeza** [comment]
I don't think it's interesting enough, and if so, it should be another module name like `hr_attendance_pivot` or similar.

**Comment by victoralmau** [comment]
OpenUpgrade: https://github.com/OCA/OpenUpgrade/pull/3616

**Pull request closed without merging**
