### PR TITLE
[14.0][IMP] hr_attendance_autoclose: move autoclose reason to settings, removing hardcoded search

### PR DESCRIPTION
**Pull request by HekkiMelody**
Currently, the `hr.attendance.reason` added to an attendance when autoclosing it is fetched via a search that hardcodes the code.

This PR creates a new per-company setting `hr_attendance_autoclose_reason`, and also moves the existing configuration field `attendance_maximum_hours_per_day` into the settings panel for consistency.

The reason to use when autoclosing is then simply accessed as a field on the current company.

### CODE REVIEW

**Comment by nimarosa** [comment]
@aleuffre Please check pre-commit errors. Then we can review.

**Comment by HekkiMelody** [comment]
It bothers me that running pre-commit locally doesn't seem to catch the issue (it was just a "tab instead of spaces" problem).

Should be fixed now, anyway.

**Comment by nimarosa** [comment]
@aleuffre Also please if you can reword your commit message according OCA guidelines. You can rename it to: 

`[14.0] [IMP] hr_attendance_autoclose: move autoclose reason to settings and remove hardcoded search`

**Review by nimarosa — APPROVED** [review]

**Comment by HekkiMelody** [comment]
Done. Thank you so much! @nimarosa

**Comment by nimarosa** [comment]
Code and Functional test okay. We can merge since it's a nice improvement to have right away. 

/ocabot merge minor

**Pull request merged**
