### PR TITLE
[14.0][MIG] hr_birthday_welcome_message: migration to 14.0

### PR DESCRIPTION
**Pull request by kluna1998**
Standard migration.

### CODE REVIEW

**Comment by etobella** [comment]
Can you rebase please?

**Comment by nimarosa** [comment]
@kluna1998 You have to rebase this yourself since you don't allowed maintainers to push to the PR branch.

**Comment by kluna1998** [comment]
> @kluna1998 You have to rebase this yourself since you don't allowed maintainers to push to the PR branch.

Done 😊

**Review by nimarosa — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by nimarosa** [comment]
Please rebase the PR on top of 14.0 branch.

**Comment by etobella** [comment]
Error seems unrelated, let's check again :thinking: 

/ocabot merge nobump

**Comment by etobella** [comment]
Error is related to hr_attendance_sheet... Any help there would be welcome

**Pull request merged**
