### PR TITLE
[16.0] mig-hr_attendance_modification_tracking

### PR DESCRIPTION
**Pull request by dalonsofl**
[MIG] hr_attendance_modification_tracking: migrate from v14.0 to v16.0

After having tried to push this PR : https://github.com/OCA/hr-attendance/pull/118 , I have decided to create one with the changes and take responsibility for the development.

### CODE REVIEW

**Review by flalexg — APPROVED** [review]
LGTM

**Review by kikopeiro — APPROVED** [review]
LGTM :+1: (without code review)

**Comment by papulo79** [comment]
LGTM

**Review by FrancoMaxime — APPROVED** [review]
LGTM: code review

**Review by amarcosg — APPROVED** [review]
LGTM!

**Pull request merged**
