### PR TITLE
Update template

### PR DESCRIPTION
**Pull request by kluna1998**
Copier update 14.0

### CODE REVIEW

**Comment by etobella** [comment]
@nimarosa @max3903 hr_attendance_sheet tests are failing, but I am unable to know why. Any help?

**Comment by max3903** [comment]
@Urvisha-OSI Can you help us here?

**Comment by etobella** [comment]
As you can see, it already fails on 14.0 base right now. https://github.com/OCA/hr-attendance/actions/runs/3429644672/jobs/5893341628

Maybe something changed on odoo base that makes the changes, I don't know... Any way, some help would be welcome here in order to review the commit I made "fixing" the tests

**Comment by Urvisha-OSI** [comment]
> As you can see, it already fails on 14.0 base right now. https://github.com/OCA/hr-attendance/actions/runs/3429644672/jobs/5893341628
> 
> Maybe something changed on odoo base that makes the changes, I don't know... Any way, some help would be welcome here in order to review the commit I made "fixing" the tests


@max3903 @etobella  all checks are passed already, and I also checked for it in my system there are not any test cases are failed, what do we want more in this PR? @etobella can you please let me know when your test case are fails ?

**Comment by etobella** [comment]
I changed the tests to make it work. Usually, this is the last thing we should do... You can see the error on the previous commits CI or main branch commit.  Can you make sure that the changes applied to the tests are right?

**Comment by Urvisha-OSI** [comment]
> I changed the tests to make it work. Usually, this is the last thing we should do... You can see the error on the previous commits CI or main branch commit. Can you make sure that the changes applied to the tests are right?

yes @etobella, the changes are right, because the old ones are not working

**Pull request merged**
