### PR TITLE
[14.0][MIG] hr_attendance_reason

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migration

### CODE REVIEW

**Comment by dalonsod** [comment]
cc @Saran440 @jarroyomorales

**Review by tonygalmiche — APPROVED** [review]
LGTM : Code review and functional review with runbot

image

Maybe we should add a kanban view?

**Review by jarroyomorales — APPROVED** [review]
Tested on runbot at LGTM! No major changes :+1:

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Comment by Saran440** [comment]
> LGTM : Code review and functional review with runbot
> 
> image
> 
> Maybe we should add a kanban view?

@tonygalmiche Yes, you can add kanban view on new pr. :)

**Pull request merged**
