### PR TITLE
[16.0][mig] hr_attendance_reason: Migration to 16.0

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by HekkiMelody — APPROVED** [review]

**Comment by HekkiMelody** [comment]
Functional review, LGTM!

**Comment by PicchiSeba** [comment]
Hi, are there any updates on this PR?

**Review by PicchiSeba — APPROVED** [review]
LGTM

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/hr-attendance/pull/124 to commit history

**Comment by tafaRU** [comment]
@dsolanki-initos could you please address https://github.com/OCA/hr-attendance/pull/112#issuecomment-1621226015?

**Review by FratiuG — APPROVED** [review]
functional test OK

**Comment by tafaRU** [comment]
@victoralmau I'd be for merging this as it is in order to also unblock https://github.com/OCA/hr-attendance/pull/116
Are you agree?

**Review by nimarosa — APPROVED** [review]

**Comment by victoralmau** [comment]
Superseed by https://github.com/OCA/hr-attendance/pull/146

**Pull request closed without merging**
