### PR TITLE
[15.0] hr_attendance_calendar_view: Add calendar view to attendance

### PR DESCRIPTION
**Pull request by jo-bloiz-ornot**

### CODE REVIEW

**Review by eicher31 — COMMENTED** [review]
I approve.

**Comment by albig** [comment]
Code is quite simple and the feature seems to be quite useful. Works for me. Thank you!

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Great contribution. Very useful to have a quick view of attendances. 

Will be great if you port this yo version 14.0 and 16.0 too. 

Merging. 

/ocabot merge nobump

**Comment by nimarosa** [comment]
Great contribution. Very useful to have a quick view of attendances.

Will be great if you port this yo version 14.0 and 16.0 too.

@jo-bloiz-ornot  I was merging it but cancelled it. Before i merge, can you squash your commits in one?

**Comment by jo-bloiz-ornot** [comment]
@nimarosa all in one commit as ask

**Pull request merged**
