### PR TITLE
[14.0][MIG] hr_attendance_report_theoretical_time

### PR DESCRIPTION
**Pull request by aphon61bank**
Standard migration.

### CODE REVIEW

**Comment by fshah-initos** [comment]
Hi @aphon61bank 
Will you please resolve the failed checks

**Review by fshah-initos — APPROVED** [review]
Code reivew. LGTM

**Comment by ao-landoo** [comment]
@fshah-initos He's not responding. I created a new PR and it's almost ready for merge. Can you check and approve my PR #37  so we can merge? Thanks!

**Comment by pedrobaeza** [comment]
Already migrated

**Pull request closed without merging**
