### PR TITLE
[ADD] hr_attendance_overtime_manual

### PR DESCRIPTION
**Pull request by fkantelberg**
This modules allows an attendance officer to generate overtime entries manually. This can be useful for system migrations to create the initial offset of overtimes or to compensate special days with extra overtime if worked on (e.g. working on national holidays or sundays gives +10% overtime to the employee).

### CODE REVIEW

**Comment by albig** [comment]
Thank for this. Adding manual overtime records is very useful in case of an initial value. I didn't find a way to set the described the percentage adjustements like you describe. Is this something the personal officer has to do manually?

**Comment by fkantelberg** [comment]
@albig Yes it's a manual process because for us it's such a rare case that it wasn't worth it. HR officer will just generate those manually

**Review by petrus-v — APPROVED** [review]

**Comment by ortlam** [comment]
@dreispt Do you have the rights to reopen this PR? I'm working on updating the branch and getting the changes merged, finally.

**Comment by OSevangelist** [comment]
Reopend based on the request of  @ortlam (fyi @dreispt)

**Comment by OSevangelist** [comment]
@ortlam @fkantelberg what is the status here. Can that already be merged?

**Comment by ortlam** [comment]
I think so, it has been reviewed. But the runboat build may be stuck.

**Comment by OSevangelist** [comment]
@fkantelberg @ortlam as there is no insight into the reason of ruboat being pending, what would be the gold standard to deal with that situation or is anybody of you aware of a solution or at least an FAQ link. One if the masters of the toolchain @sbidoul has an answer. Can we simply try to merge this or any idea how to deal with pending states in Ruboat ?

**Comment by ortlam** [comment]
@OSevangelist A force push fixed it.

**Comment by sbidoul** [comment]
At some point, runboat builds expire to make room for new builds. You need to push to force a new build, indeed.

**Comment by ortlam** [comment]
@OSevangelist I checked the codecov CI, the module is reported as completely covered by the tests, so I don't know why it reports a 0.02% drop. I think we can ignore that and merge this. It has been approved once.

**Pull request merged**
