### PR TITLE
[15.0][OU-ADD] hr_attendance_reason: Rename res.company field

### PR DESCRIPTION
**Pull request by victoralmau**
Rename res.company field (related to https://github.com/OCA/hr-attendance/pull/124/commits/2b77bf2c04f5507609969418536598db53df8122)

Please @pedrobaeza can you review it?

@Tecnativa TT40897

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But did this land on any merged branch? If not, this script is not correct and you just must execute it locally in the DB.

**Comment by victoralmau** [comment]
This change is related to https://github.com/OCA/hr-attendance/pull/124.

It is already merged and changed version with https://github.com/OCA/hr-attendance/commit/9c4991a04e2ae5f6caa942fcc84817bab7dda45d but I realized that this renaming is necessary.

**Comment by pedrobaeza** [comment]
But the field name change was done still being in PR, so no need of this.

**Review by pedrobaeza — APPROVED** [review]
Seen that it was that way in 14.0:

https://github.com/OCA/hr-attendance/blob/14.0/hr_attendance_reason/models/res_company.py#L10

**Pull request merged**
